from __future__ import annotations

from sqlalchemy.orm import Session

from .models import CompetitorInsight, ProductOpportunity

SAMPLE_OPPORTUNITIES = [
    {
        "product_name": "Personalized Birth Flower Name Necklace",
        "platform": "Etsy",
        "category": "Personalized gifts",
        "trend_status": "Rising",
        "competition_level": "Medium",
        "average_price": "$28-$58",
        "target_customer": "Women buying thoughtful birthday, bridesmaid, mom, and girlfriend gifts.",
        "primary_keywords": "birth flower necklace, personalized name necklace, custom floral jewelry, handmade necklace",
        "long_tail_keywords": "personalized birth flower necklace for mom, custom name flower necklace gift, dainty floral necklace handmade",
        "title_structure": "Primary keyword + personalization angle + recipient + gift occasion + material.",
        "description_style": "Emotional gift-led copy, personalization steps, material details, packaging promise, care notes.",
        "visual_style": "Warm neutral flat lay, macro pendant detail, model neck shot, gift box photo, personalization close-up.",
        "competitor_learnings": "Top listings emphasize birth month meaning, fast personalization, gift-ready packaging, and simple variants.",
        "viral_reason": "Combines identity, astrology-adjacent symbolism, giftability, and highly shareable before/after personalization visuals.",
        "edel_luxe_fit": "Very strong fit: premium, sentimental, handmade-feeling, and easy to position as an elegant keepsake.",
        "suggested_etsy_title": "Birth Flower Name Necklace, Personalized Floral Jewelry, Custom Gift for Mom, Dainty Handmade Necklace",
        "seo_description": "Create a meaningful keepsake with a dainty birth flower name necklace designed for everyday elegance. Choose the flower month, name, finish, and gift-ready packaging for a personal birthday, bridesmaid, mom, or girlfriend gift. Data note: pricing and trend signals are sample estimates until live marketplace APIs are connected.",
        "etsy_tags": "birth flower, name necklace, custom necklace, flower necklace, mom gift, birthday gift, dainty jewelry, floral jewelry, bridesmaid gift, handmade gift, keepsake gift, personalized, women gift",
        "photo_advice": "Use cream silk, a handwritten card, soft daylight, and one short lifestyle reel showing engraving/customization reveal.",
        "product_development_idea": "Offer optional tiny birthstone charm and premium message-card bundles for mother-daughter gifting.",
        "sales_potential_score": 91,
        "estimated_sales_potential": "High (estimate)",
        "trend_score": 88.0,
        "source_url": "https://www.etsy.com/search?q=birth+flower+name+necklace",
        "data_confidence": "Sample seed data; validate with live Etsy data before buying inventory.",
        "first_action_plan": "Prototype 3 finishes, create 5 SEO listings by recipient, photograph gift packaging, test $38-$48 price band.",
    },
    {
        "product_name": "Angel Number Bracelet with Message Card",
        "platform": "TikTok Shop",
        "category": "Spiritual / symbolic jewelry",
        "trend_status": "Viral-prone",
        "competition_level": "Low-Medium",
        "average_price": "$16-$34",
        "target_customer": "Gen Z and millennial women interested in manifestation, affirmations, and affordable gifts.",
        "primary_keywords": "angel number bracelet, 111 bracelet, manifestation jewelry, spiritual bracelet",
        "long_tail_keywords": "angel number bracelet with message card, 111 manifestation bracelet gift, spiritual handmade bracelet for women",
        "title_structure": "Angel number + spiritual promise + material/style + gift recipient.",
        "description_style": "Short emotional hook, meaning of number, stackable styling, gift-card story, social proof prompt.",
        "visual_style": "UGC hand shots, unboxing video, close-up of card meaning, stacked bracelets, candle/crystal props.",
        "competitor_learnings": "Viral videos lead with the message-card meaning first, then reveal the bracelet as an affordable emotional gift.",
        "viral_reason": "Spiritual meaning is instantly explainable in short video and encourages comments like 'I keep seeing 111'.",
        "edel_luxe_fit": "Good fit if upgraded with premium beads, gold-filled accents, and elegant branded meaning cards.",
        "suggested_etsy_title": "Angel Number Bracelet 111, Manifestation Jewelry Gift, Spiritual Bracelet with Meaning Card for Women",
        "seo_description": "A delicate angel number bracelet made for meaningful everyday wear. Each piece includes a premium meaning card, making it a thoughtful spiritual gift for encouragement, manifestation, birthdays, and self-love rituals. Data note: viral signals are estimated from sample research until TikTok Shop/social APIs are connected.",
        "etsy_tags": "angel number, 111 bracelet, spiritual gift, manifestation, bracelet gift, women bracelet, meaning card, self love gift, crystal bracelet, dainty bracelet, handmade, gift for her, affirmation",
        "photo_advice": "Shoot vertical UGC: hook text overlay, card close-up, bracelet on wrist, packaged order reveal.",
        "product_development_idea": "Create 111, 222, 333, 444 variants and bundle a mini affirmation card set.",
        "sales_potential_score": 86,
        "estimated_sales_potential": "High (estimate)",
        "trend_score": 84.0,
        "source_url": "https://www.tiktok.com/search?q=angel%20number%20bracelet",
        "data_confidence": "Sample seed data; validate with current TikTok Shop and social metrics.",
        "first_action_plan": "Launch 4 angel number SKUs, record 10 UGC videos, A/B test card-first versus bracelet-first thumbnails.",
    },
    {
        "product_name": "Pressed Flower Resin Initial Ring Dish",
        "platform": "Pinterest",
        "category": "Trend handmade accessories",
        "trend_status": "Seasonal rising",
        "competition_level": "Medium",
        "average_price": "$18-$42",
        "target_customer": "Gift buyers seeking bridesmaid, engagement, dorm, or desk decor add-ons.",
        "primary_keywords": "ring dish, pressed flower ring dish, initial jewelry tray, bridesmaid gift",
        "long_tail_keywords": "pressed flower initial ring dish, personalized resin jewelry tray, bridesmaid ring dish gift",
        "title_structure": "Object keyword + material motif + personalization + occasion.",
        "description_style": "Decorative gift copy with personalization details, handmade uniqueness disclaimer, and care instructions.",
        "visual_style": "Bright pin-friendly overhead photos, pastel backgrounds, flowers arranged around initials, jewelry in tray.",
        "competitor_learnings": "Pins perform well when the use case is obvious: rings displayed in a customized tray next to packaging.",
        "viral_reason": "Highly visual, giftable, customizable, and easy for Pinterest users to save for wedding or room inspiration boards.",
        "edel_luxe_fit": "Good adjacent product: supports jewelry bundles and raises average order value without leaving handmade gifting.",
        "suggested_etsy_title": "Pressed Flower Ring Dish, Personalized Initial Jewelry Tray, Handmade Bridesmaid Gift, Resin Keepsake",
        "seo_description": "A handmade pressed flower ring dish that turns everyday jewelry storage into a personal keepsake. Add an initial for a thoughtful bridesmaid, engagement, birthday, or dorm gift. Data note: Pinterest save potential is estimated from seed research until live pin metrics are connected.",
        "etsy_tags": "ring dish, jewelry tray, pressed flower, resin tray, initial gift, bridesmaid gift, handmade tray, ring holder, keepsake dish, wedding gift, dorm decor, personalized, gift for her",
        "photo_advice": "Design tall 2:3 Pinterest images with visible initials, rings in the tray, and a soft pastel headline overlay.",
        "product_development_idea": "Bundle with Edel Luxe rings or offer wedding party sets of 4-8 dishes.",
        "sales_potential_score": 79,
        "estimated_sales_potential": "Medium-High (estimate)",
        "trend_score": 76.0,
        "source_url": "https://www.pinterest.com/search/pins/?q=pressed%20flower%20ring%20dish",
        "data_confidence": "Sample seed data; validate with Pinterest Trends and Etsy competition count.",
        "first_action_plan": "Make 5 colorways, pin 15 vertical images, test bundle discount with personalized rings.",
    },
    {
        "product_name": "Morse Code Secret Message Necklace",
        "platform": "Amazon Handmade",
        "category": "Keepsake jewelry",
        "trend_status": "Steady niche",
        "competition_level": "Low-Medium",
        "average_price": "$24-$46",
        "target_customer": "Gift buyers wanting subtle personalization for couples, friends, sisters, and moms.",
        "primary_keywords": "morse code necklace, secret message necklace, personalized necklace, minimalist jewelry",
        "long_tail_keywords": "morse code necklace custom message, secret message necklace for girlfriend, minimalist personalized gift for her",
        "title_structure": "Niche keyword + secret/personalized angle + recipient + material.",
        "description_style": "Explain the hidden message concept, personalization limit, gift story, and premium materials.",
        "visual_style": "Clean white background for marketplace, macro bead sequence, message-card translation, model neckline shot.",
        "competitor_learnings": "Successful listings reduce confusion by showing the coded word and decoded message in the first image carousel.",
        "viral_reason": "The hidden-message concept creates curiosity and emotional reveal, suitable for short-form content and gift guides.",
        "edel_luxe_fit": "Strong fit: elegant, symbolic, personalized, and differentiated from generic name necklaces.",
        "suggested_etsy_title": "Morse Code Necklace, Secret Message Jewelry, Personalized Gift for Her, Minimalist Handmade Necklace",
        "seo_description": "Send a private message in a refined Morse code necklace handcrafted for meaningful everyday wear. Choose a short word, name, or affirmation and include a premium decoder card for a memorable reveal. Data note: demand and competition are sample estimates until live marketplace data is connected.",
        "etsy_tags": "morse code, secret message, custom necklace, gift for her, minimalist, personalized, girlfriend gift, sister gift, mom gift, dainty jewelry, handmade, keepsake, coded necklace",
        "photo_advice": "Show the same necklace with a decoder card, a close macro crop, and one romantic gift-box reveal photo.",
        "product_development_idea": "Create pre-set words like LOVE, MAMA, HOPE plus custom input for faster production.",
        "sales_potential_score": 83,
        "estimated_sales_potential": "Medium-High (estimate)",
        "trend_score": 72.0,
        "source_url": "https://www.amazon.com/s?k=morse+code+necklace+handmade",
        "data_confidence": "Sample seed data; validate with Amazon Handmade search and review density.",
        "first_action_plan": "Build decoder card template, test 6 pre-set keywords, compare Amazon Handmade and Etsy title variants.",
    },
]

SAMPLE_COMPETITORS = [
    {
        "shop_name": "Personalized floral jewelry sellers",
        "platform": "Etsy",
        "niche": "Birth flower necklaces",
        "best_selling_products": "Birth flower name necklaces, birthstone charm necklaces, mom gift bundles.",
        "pricing_strategy": "Entry variants around $28-$34, premium plated or sterling versions around $45-$60, frequent 10-25% sale badges.",
        "seo_patterns": "Front-loads 'birth flower necklace' and repeats recipient keywords such as mom, bridesmaid, girlfriend, birthday gift.",
        "visual_style": "Neutral backgrounds, model neck shots, engraved pendant close-ups, gift packaging carousel images.",
        "trust_signals": "High review counts, bestseller badges, personalization instructions, processing-time clarity, gift-ready packaging.",
        "shipping_promotions": "Free shipping threshold, limited-time sale, upgradeable rush processing.",
        "opportunity_gap": "Premium brand storytelling and better personalization previews can differentiate Edel Luxe from template-heavy listings.",
        "source_url": "https://www.etsy.com/search?q=birth+flower+necklace",
        "data_confidence": "Sample competitor pattern; run live scan for exact shops.",
    },
    {
        "shop_name": "Spiritual gift UGC brands",
        "platform": "TikTok Shop",
        "niche": "Angel number and manifestation jewelry",
        "best_selling_products": "Angel number bracelets, affirmation necklaces, crystal bead stacks with cards.",
        "pricing_strategy": "Impulse-friendly $14-$29 price points, bundles of 2-4 items, creator coupons.",
        "seo_patterns": "Uses short emotional phrases: angel number bracelet, manifestation gift, protection bracelet, self-love jewelry.",
        "visual_style": "Creator-style videos, hooks in first 2 seconds, card meaning close-ups, unboxing and wrist-stack shots.",
        "trust_signals": "UGC volume, creator testimonials, visible packaging, fast shipping badge where available.",
        "shipping_promotions": "Flash deals, TikTok coupons, bundles, limited stock messaging.",
        "opportunity_gap": "Most competitors look mass-produced; a handmade premium version with elegant cards can command Etsy pricing.",
        "source_url": "https://www.tiktok.com/search?q=manifestation%20bracelet",
        "data_confidence": "Sample competitor pattern; validate through live social/shop data.",
    },
]


def seed_database(db: Session) -> None:
    if db.query(ProductOpportunity).count() == 0:
        db.add_all(ProductOpportunity(**item) for item in SAMPLE_OPPORTUNITIES)
    if db.query(CompetitorInsight).count() == 0:
        db.add_all(CompetitorInsight(**item) for item in SAMPLE_COMPETITORS)
    db.commit()
